export const USE_IDEA_EVENT = "copilot:use-idea";
export const IDEA_MAX_LENGTH = 300;

export type IdeaStatus = "clear" | "adjacent" | "house";

export type IdeaExample = {
  id: string;
  name: string;
  category: string;
  status: IdeaStatus;
  effort: 2 | 3 | 4 | null;
  pitch: string;
  edge: string;
  risk: string;
  inspiration: string | null;
};

export const IDEA_EXAMPLES: IdeaExample[] = [
  {
    id: "spread-mine",
    name: "Spread Mine",
    category: "Jogo onchain · liquidez",
    status: "clear",
    effort: 4,
    pitch: "Um jogo de mineração onchain em que o trabalho é market making de verdade: o minerador só ganha emissões pela liquidez que ficou cotada dentro de uma faixa de spread, pelo tempo medido no estado do pool. Foco em pools de ações tokenizadas na Meteora.",
    edge: "A mineração de liquidez clássica paga por TVL parado. Aqui a recompensa mede o serviço: a distância da liquidez até o preço ativo e o tempo de presença.",
    risk: "Continua sendo emissão de token. Toda mineração de liquidez acabou quando a emissão acabou, então a pergunta é o que fica de pé depois.",
    inspiration: "ORE e os jogos de mineração da Solana",
  },
  {
    id: "provable",
    name: "Provable",
    category: "Mercados de previsão",
    status: "adjacent",
    effort: 3,
    pitch: "Uma biblioteca de resolvedores onchain e uma fábrica de mercados para a Solana: qualquer app lista mercados sobre o que a própria rede já sabe, como supply de token, votos de DAO ou TVL de protocolo, e a resolução é uma leitura, não um julgamento.",
    edge: "É uma biblioteca, não uma casa de apostas. Cada resolvedor é um programa versionado e auditável, fixado no mercado na hora da criação.",
    risk: "O problema é demanda, não viabilidade. Mercados sobre métricas de protocolo e votos de DAO costumam ser os que ninguém negocia.",
    inspiration: "Mercados de previsão com oráculos na Solana",
  },
  {
    id: "consent-receipt-registry",
    name: "Consent Receipt Registry",
    category: "Infra de IA",
    status: "adjacent",
    effort: 3,
    pitch: "Um registro na Solana que publica o recibo dos dados de treino de IA, não o dado: hash do conteúdo, termos de consentimento, licença, prova de pagamento e data. O laboratório prova a origem do corpus e quem contribuiu prova que foi pago.",
    edge: "Publica o recibo e guarda o ativo. O dono do conteúdo só entrega um hash e um termo assinado, e a obra nunca sai do controle dele.",
    risk: "O comprador talvez ainda não exista. Um registro voluntário só ganha valor quando um regulador ou um tribunal passar a exigir prova de origem.",
    inspiration: "Projetos de propriedade intelectual onchain que migraram para dados de IA",
  },
  {
    id: "weekend-gap-guard",
    name: "Weekend Gap Guard",
    category: "Ações tokenizadas",
    status: "adjacent",
    effort: 3,
    pitch: "Um cofre que só paga dívida, com um keeper que vigia seu empréstimo com ações tokenizadas de colateral e quita parte dele com uma reserva de USDC quando o LTV passa do seu limite com a bolsa fechada. Um gap de fim de semana não liquida você dormindo.",
    edge: "A maioria das proteções é um bot com poder de saque. Aqui o cofre só libera a reserva se a instrução de pagamento da dívida estiver na mesma transação.",
    risk: "É uma funcionalidade, não uma empresa: o protocolo de empréstimo pode lançar o mesmo recurso. E a reserva parada custa eficiência de capital.",
    inspiration: "Projetos open source de proteção contra liquidação na Solana",
  },
  {
    id: "sessionguard",
    name: "SessionGuard",
    category: "Infra DeFi",
    status: "adjacent",
    effort: 3,
    pitch: "Um oráculo onchain de sessão de pregão, com uma checagem que outros programas chamam por CPI: o mercado do ativo estar fechado vira um estado de primeira classe para qualquer pool, cofre ou mercado de empréstimo que toque uma ação tokenizada.",
    edge: "Entrega o calendário de pregão como infraestrutura compartilhada, em vez de cada protocolo colar o seu: regular, estendido, overnight, fechado e feriado.",
    risk: "Calendário de pregão é dado offchain, então precisa de um publicador confiável. Uma atualização errada ou atrasada é pior do que nenhuma.",
    inspiration: "Discussões abertas em SDKs de protocolos de ações tokenizadas",
  },
  {
    id: "consorcio-de-sol",
    name: "Consórcio de SOL",
    category: "Staking",
    status: "house",
    effort: null,
    pitch: "Um consórcio de stake de SOL: vários stakers se juntam e, a cada período, a recompensa total do stake vai para um participante contemplado. Quem quiser pode dar lances para aumentar a chance, como num consórcio brasileiro.",
    edge: "Usa um formato que o brasileiro já conhece e encaixa bem em modelos de stake para acessar um produto ou uma funcionalidade.",
    risk: "Ainda não passou pela varredura. Pesquise projetos de poupança com sorteio antes de começar.",
    inspiration: null,
  },
  {
    id: "treino-que-rende",
    name: "Treino que rende",
    category: "Consumo · saúde",
    status: "house",
    effort: null,
    pitch: "Um app de exercício que paga pelos seus dados: o usuário se grava alongando ou treinando e escolhe uma trilha por semana, como mobilidade, força ou resistência. A trilha define o ativo da recompensa, pago em ações tokenizadas.",
    edge: "Parte do move-to-earn, mas remunera um dado útil, o vídeo do exercício, e paga em ativos que já têm valor fora do app.",
    risk: "Ainda não passou pela varredura. Pesquise os apps de move-to-earn e por que perderam os usuários antes de começar.",
    inspiration: null,
  },
  {
    id: "touchstone",
    name: "Touchstone",
    category: "Agentes de IA",
    status: "clear",
    effort: 2,
    pitch: "Um auditor que compra para conferir, e um diretório, para a economia x402 da Solana: ele paga cada endpoint listado, compara a resposta com o schema que o vendedor declarou e publica um veredito assinado onchain, que os agentes leem antes de gastar.",
    edge: "Verifica comprando, não acreditando na palavra do vendedor. É um cliente oculto para o comércio entre máquinas.",
    risk: "É a menos defensável da lista: um crawler, um pagador e uma tabela. Quem mantém o padrão pode lançar um registro oficial e encerrar a categoria.",
    inspiration: "Projetos que atacam a falta de confiança no x402",
  },
  {
    id: "precedent",
    name: "Precedent",
    category: "Dados · mercados de previsão",
    status: "clear",
    effort: 2,
    pitch: "O histórico de resolução dos mercados de eventos: uma base consultável com a redação de cada mercado, o resolvedor, a evidência citada, as contestações, as reversões e o tempo até a decisão final, juntando várias plataformas.",
    edge: "Indexa o que ninguém indexa. Os produtos de dados capturam preço e volume, e este captura o ciclo de vida da resolução.",
    risk: "Menor risco e menor teto da lista: base de dados em cripto é difícil de monetizar e os compradores óbvios são poucos.",
    inspiration: "As disputas de resolução em mercados de previsão",
  },
  {
    id: "order-flow-attribution",
    name: "Order-Flow Attribution SDK",
    category: "Roteamento · monetização",
    status: "clear",
    effort: 3,
    pitch: "Uma integração única para qualquer carteira, bot ou agente de trading da Solana anexar um código de taxa a uma ordem de perp e receber pelo fluxo, em várias plataformas, com um só escrow e um só livro de receita.",
    edge: "Hoje cada plataforma tem o próprio esquema de atribuição, então quem integra três faz o trabalho três vezes. Aqui a atribuição vira uma camada portátil.",
    risk: "Intermediário entre carteira e plataforma é fácil de cortar pelos dois lados: as plataformas querem seus próprios programas e as carteiras grandes integram direto.",
    inspiration: "Builder codes da Hyperliquid",
  },
  {
    id: "blockspace-value-rebate",
    name: "Blockspace Value Rebate",
    category: "Infra da rede",
    status: "clear",
    effort: 4,
    pitch: "Uma camada de atribuição e reembolso que identifica qual app da Solana gerou cada unidade de taxa de prioridade e de gorjeta, e devolve ao app uma parte combinada desse valor, vinda de validadores e construtores de bloco.",
    edge: "Transforma a demanda que o app cria em uma linha de receita. A atribuição onchain por app ainda não existe na Solana.",
    risk: "Atribuir é difícil: uma transação passa por um agregador e toca vários programas, e não há resposta única para qual app a gerou. Dá para burlar roteando o próprio fluxo.",
    inspiration: "Monetização de taxas da Sonic e builder codes da Hyperliquid",
  },
  {
    id: "backstop",
    name: "Backstop",
    category: "Seguros · mercados de previsão",
    status: "clear",
    effort: 4,
    pitch: "Seguro contra resolução errada, vendido junto com a posição em um mercado de previsão: uma apólice por mercado que paga se ele for liquidado contra a evidência documentada, revertido, anulado ou ficar sem pagar além do prazo.",
    edge: "Trata a resolução errada como um risco segurável e precificado à parte. Um histórico de disputas permite cobrar prêmios diferentes por tipo de mercado.",
    risk: "Os sinistros são correlacionados e adversariais: um incidente em uma plataforma atinge todas as apólices de uma vez, e o gatilho da apólice é difícil de definir.",
    inspiration: "As falhas de resolução em mercados de previsão",
  },
  {
    id: "nav-arb-pool",
    name: "NAV Arb Pool",
    category: "Ações tokenizadas",
    status: "clear",
    effort: 4,
    pitch: "Um pool que junta os tokens de pequenos detentores de ações tokenizadas para atingir o mínimo de resgate do emissor e faz arbitragem de criação e resgate contra o preço onchain, para o mercado primário segurar a paridade na prática.",
    edge: "Isola a única parte que não pode ser permissionless, o operador com KYC que envia os resgates, e deixa o resto onchain e proporcional.",
    risk: "Depende de um operador com KYC e relação com o emissor, que pode mudar os termos. Operar o pool pode ser atividade regulada, conforme a jurisdição.",
    inspiration: "A distância entre o preço onchain e o resgate nas ações tokenizadas",
  },
  {
    id: "proof-of-alive",
    name: "Proof of Alive",
    category: "Agentes de IA",
    status: "adjacent",
    effort: 3,
    pitch: "Um verificador contínuo que testa o endpoint declarado de cada agente registrado, confere schema, latência e taxa de sucesso, e grava atestados assinados e com caução no registro de agentes da Solana, para os compradores filtrarem os que estão mortos.",
    edge: "Todo mundo constrói registros e ninguém constrói o auditor que dá sentido a uma entrada. O agente deposita uma caução, cortada se o endpoint mentir ou cair.",
    risk: "Os registros podem ser só vitrine. Se ninguém lê as entradas, um bom auditor fica sem comprador.",
    inspiration: "Levantamentos de registros de agentes no padrão ERC-8004",
  },
  {
    id: "stake-to-call",
    name: "Stake to Call",
    category: "Agentes de IA",
    status: "adjacent",
    effort: 3,
    pitch: "Limite de uso resistente a contas falsas para endpoints sem cadastro: quem chama trava uma caução pequena e reembolsável ligada a uma chave, o endpoint lê uma cota que pesa caução e histórico, e quem abusa perde a caução. Sem voltar às API keys.",
    edge: "Usa a caução como identidade, não como pagamento. Quem chama muito e bem trava capital uma vez, e o custo cai só em quem abusa.",
    risk: "O mais provável é que os operadores não queiram: API key funciona, é grátis e todo mundo já tem. E travar capital afasta os pequenos.",
    inspiration: "A escolha do x402 de não ter contas nem assinaturas",
  },
  {
    id: "spendable-allocation-credits",
    name: "Spendable Allocation Credits",
    category: "Distribuição de tokens",
    status: "adjacent",
    effort: 3,
    pitch: "Um motor de alocação onchain em que a carteira acumula créditos não transferíveis todo dia, por uso e saldo em uma janela móvel, e gasta esses créditos para pegar alocações de lançamentos. Leva quem participa de forma contínua, não quem aparece no snapshot.",
    edge: "Crédito é fluxo, não foto. E é gasto no resgate, então cada alocação tem um custo de oportunidade.",
    risk: "O modelo original funciona atrás de uma exchange com KYC. Sem isso, um atacante divide o capital em centenas de carteiras e ganha centenas de fluxos de crédito.",
    inspiration: "Binance Alpha Points",
  },
  {
    id: "upkeep",
    name: "Upkeep",
    category: "Agentes de IA · tokens",
    status: "adjacent",
    effort: 3,
    pitch: "Uma primitiva aberta que transforma as taxas de criador de um token da Solana no orçamento de inferência do agente dele: as taxas caem em uma conta de computação medida, cada chamada de modelo é debitada onchain e qualquer um confere quantos dias de fôlego restam.",
    edge: "A solvência do agente vira um fato público e verificável. Hoje, agente autônomo quer dizer que alguém recarrega uma chave de API em silêncio.",
    risk: "A categoria está encolhendo e o custo de inferência cai sem parar, o que diminui o problema que a ideia resolve.",
    inspiration: "Agentes com carteira e token próprios",
  },
  {
    id: "quote-asset-hedge-vaults",
    name: "Quote-Asset Hedge Vaults",
    category: "Ações tokenizadas",
    status: "adjacent",
    effort: 3,
    pitch: "Um cofre para prover liquidez em pools cotados em ações tokenizadas, como SPYx ou QQQx, fazendo hedge contínuo do beta da ponta de cotação. O LP ganha as taxas do launchpad sem carregar, sem querer, uma posição comprada e alavancada em bolsa.",
    edge: "Cofres de hedge para LP existem para pares de cripto. Nenhum trata o caso em que o instrumento de hedge fica fechado boa parte da semana enquanto o pool negocia sem parar.",
    risk: "Depende de um launchpad novo, e volume de launchpad é reflexivo. Se a moda passar, o mercado some.",
    inspiration: "Launchpads que cotam tokens novos em ações tokenizadas",
  },
];

export function ideaAgentPrompt(idea: IdeaExample): string {
  return `Quero construir isto no hackathon do Colosseum: ${idea.pitch} Alguém já fez isso nos hackathons do Colosseum? Como está o cenário competitivo, o que os projetos anteriores erraram e onde ainda há espaço? Termine com uma avaliação honesta: vale a pena seguir com essa ideia ou não?`;
}
